"use client";

import { useEffect, useMemo, useState } from "react";
import RequireAuth from "@/components/RequireAuth";
import ScreenHeader from "@/components/ScreenHeader";
import MessageModal from "@/components/MessageModal";
import useAdminStatus from "@/components/useAdminStatus";
import { supabase } from "@/lib/supabase";

type EmailMeta = {
  recipient?: string | null;
  subject?: string | null;
  provider?: string | null;
  sender?: string | null;
  competition?: string | null;
  message_id?: string | null;
  error?: string | null;
  email_sent?: boolean | null;
  email_error?: string | null;
  email_type?: string | null;
};

type EmailRow = {
  id: string;
  created_at: string;
  action: string;
  summary: string | null;
  meta: EmailMeta | null;
};

type StatusFilter = "all" | "sent" | "failed";
type TypeFilter = "all" | "registration" | "password" | "booking";

const emailActions = [
  "competition_welcome_sent",
  "competition_welcome_failed",
  "competition_welcome_skipped",
  "email_invitation_sent",
  "email_invitation_failed",
  "password_reset_link_sent",
  "password_reset_link_failed",
  "table_booking_accepted",
  "table_booking_rejected",
  "table_booking_deleted",
];

function emailType(row: EmailRow) {
  if (row.action.startsWith("competition_welcome")) return { key: "registration" as const, label: "Competition welcome" };
  if (row.action.startsWith("password_reset")) return { key: "password" as const, label: "Password reset" };
  if (row.action.startsWith("table_booking")) return { key: "booking" as const, label: row.meta?.email_type || "Table booking" };
  return { key: "registration" as const, label: "Registration invitation" };
}

function emailWasSent(row: EmailRow) {
  if (row.action.startsWith("table_booking")) return row.meta?.email_sent === true;
  return row.action.endsWith("_sent");
}

function failureDetail(row: EmailRow) {
  return row.meta?.error || row.meta?.email_error || row.summary || "The email could not be sent.";
}

export default function EmailsPage() {
  const admin = useAdminStatus();
  const [rows, setRows] = useState<EmailRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [typeFilter, setTypeFilter] = useState<TypeFilter>("all");
  const [message, setMessage] = useState<string | null>(null);

  useEffect(() => {
    const load = async () => {
      if (admin.loading) return;
      if (!admin.isSuper) {
        setLoading(false);
        return;
      }
      if (!supabase) {
        setMessage("Supabase is not configured.");
        setLoading(false);
        return;
      }
      const result = await supabase
        .from("audit_logs")
        .select("id,created_at,action,summary,meta")
        .in("action", emailActions)
        .order("created_at", { ascending: false })
        .limit(1000);
      if (result.error) setMessage(result.error.message);
      else setRows((result.data ?? []) as EmailRow[]);
      setLoading(false);
    };
    void load();
  }, [admin.loading, admin.isSuper]);

  const totals = useMemo(() => {
    const sent = rows.filter(emailWasSent).length;
    return { total: rows.length, sent, failed: rows.length - sent };
  }, [rows]);

  const filtered = useMemo(() => {
    const value = query.trim().toLowerCase();
    return rows.filter((row) => {
      const type = emailType(row);
      const sent = emailWasSent(row);
      if (typeFilter !== "all" && type.key !== typeFilter) return false;
      if (statusFilter === "sent" && !sent) return false;
      if (statusFilter === "failed" && sent) return false;
      if (!value) return true;
      return [row.meta?.recipient, row.meta?.subject, row.meta?.competition, row.meta?.sender, row.meta?.message_id, row.summary]
        .filter(Boolean)
        .some((field) => String(field).toLowerCase().includes(value));
    });
  }, [query, rows, statusFilter, typeFilter]);

  return (
    <main className="min-h-screen bg-slate-100 p-4 sm:p-6">
      <div className="mx-auto max-w-6xl space-y-4">
        <RequireAuth>
          <ScreenHeader title="System Email Activity" eyebrow="Admin" subtitle="Track emails generated by Rack & Frame." />
          {!admin.loading && !admin.isSuper ? (
            <section className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900">
              Only the Super User can access System Email Activity.
            </section>
          ) : null}
          {admin.isSuper ? (
            <>
              <section className="rounded-2xl border border-teal-200 bg-teal-50 p-4 text-sm text-teal-950">
                <p><strong>Current email provider:</strong> Resend</p>
                <p><strong>Password-reset sender:</strong> Rack &amp; Frame &lt;no-reply@mail.rackandframe.app&gt;</p>
                <p><strong>Automatic BCC:</strong> None</p>
                <p className="mt-2 text-teal-800">A “Sent” entry means Resend accepted the message. Delivery, bounce and spam details remain available in the Resend dashboard.</p>
              </section>

              <section className="grid gap-3 sm:grid-cols-3">
                <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
                  <p className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Recorded</p>
                  <p className="mt-1 text-3xl font-black text-slate-950">{totals.total}</p>
                </div>
                <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 shadow-sm">
                  <p className="text-xs font-semibold uppercase tracking-[0.18em] text-emerald-700">Sent</p>
                  <p className="mt-1 text-3xl font-black text-emerald-900">{totals.sent}</p>
                </div>
                <div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 shadow-sm">
                  <p className="text-xs font-semibold uppercase tracking-[0.18em] text-rose-700">Failed</p>
                  <p className="mt-1 text-3xl font-black text-rose-900">{totals.failed}</p>
                </div>
              </section>

              <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
                <div className="grid gap-2 lg:grid-cols-[minmax(0,1fr)_220px_180px]">
                  <input
                    className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm"
                    placeholder="Search recipient, subject, sender or competition..."
                    value={query}
                    onChange={(event) => setQuery(event.target.value)}
                  />
                  <select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value as TypeFilter)} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm">
                    <option value="all">All email types</option>
                    <option value="registration">Registration invitations</option>
                    <option value="password">Password resets</option>
                    <option value="booking">Table bookings</option>
                  </select>
                  <select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as StatusFilter)} className="rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm">
                    <option value="all">All statuses</option>
                    <option value="sent">Sent</option>
                    <option value="failed">Failed</option>
                  </select>
                </div>
                <MessageModal message={message} onClose={() => setMessage(null)} />
                {loading ? <p className="mt-4 text-sm text-slate-600">Loading email activity...</p> : null}
                {!loading && filtered.length === 0 ? <p className="mt-4 text-sm text-slate-600">No matching email activity.</p> : null}
                {!loading && filtered.length ? (
                  <div className="mt-4 overflow-auto rounded-xl border border-slate-200">
                    <table className="min-w-full text-sm">
                      <thead className="bg-slate-50">
                        <tr>
                          <th className="px-3 py-2 text-left">When</th>
                          <th className="px-3 py-2 text-left">Status</th>
                          <th className="px-3 py-2 text-left">Type</th>
                          <th className="px-3 py-2 text-left">Recipient</th>
                          <th className="px-3 py-2 text-left">Subject</th>
                          <th className="px-3 py-2 text-left">Provider details</th>
                        </tr>
                      </thead>
                      <tbody>
                        {filtered.map((row) => {
                          const sent = emailWasSent(row);
                          const type = emailType(row);
                          return (
                            <tr key={row.id} className="border-t border-slate-200 align-top">
                              <td className="whitespace-nowrap px-3 py-3 text-slate-700">{new Date(row.created_at).toLocaleString("en-GB")}</td>
                              <td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${sent ? "bg-emerald-100 text-emerald-800" : "bg-rose-100 text-rose-800"}`}>{sent ? "Sent" : "Failed"}</span></td>
                              <td className="whitespace-nowrap px-3 py-3 font-medium text-slate-800">{type.label}</td>
                              <td className="px-3 py-3 text-slate-900">{row.meta?.recipient ?? "Not recorded"}</td>
                              <td className="min-w-[220px] px-3 py-3 text-slate-700">
                                <p>{row.meta?.subject ?? row.summary ?? "-"}</p>
                                {row.meta?.competition ? <p className="mt-1 text-xs text-slate-500">{row.meta.competition}</p> : null}
                              </td>
                              <td className="min-w-[220px] px-3 py-3 text-slate-600">
                                {sent ? (
                                  <>
                                    <p>{row.meta?.provider ?? "Resend"}</p>
                                    {row.meta?.sender ? <p className="mt-1 text-xs">From: {row.meta.sender}</p> : null}
                                    {row.meta?.message_id ? <p className="mt-1 break-all text-xs text-slate-500">ID: {row.meta.message_id}</p> : null}
                                  </>
                                ) : <p className="text-rose-700">{failureDetail(row)}</p>}
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                ) : null}
              </section>
            </>
          ) : null}
        </RequireAuth>
      </div>
    </main>
  );
}
